continue-on-error

diff --git a/.github/workflows/multi-job.yml b/.github/workflows/multi-job.yml
--- a/.github/workflows/multi-job.yml
+++ b/.github/workflows/multi-job.yml
@@ -50,4 +50,17 @@ jobs:
               run: echo " Deploying"
             - name: Get the output from test job and print here
               run: echo "Output from test ${{ needs.test.outputs.date }}"
+            - name: Manual fail
+              id: fail_step
+              run: exit 1
+            - name: Rn when previous step fails
+              if: failure()
+              run: echo "Previous step failed, so this step is running"
+            - name: Step with the continue-on-error
+              continue-on-error: true
+              run: |
+                echo: " This step will fail but the worklow continues"
+                exit 1
+            - name: Workflow continue
+              run: echo "workflow did not stop on failure, and continue-on-error"
 
